### ISSUE TITLE
Error on chart click

### ISSUE THREAD

**Issue by AndreaChumioque** [amcharts/amcharts4#4416]
**Bug description**

Error shows in the console when clicking any part of the chart.
The graph renders correctly but the error keeps showing.

```
Uncaught TypeError: n.includes is not a function
    at index.js:2:1
    at Array.some (<anonymous>)
    at HTMLDocument.<anonymous> (index.js:2:1)
```

I am working with React 17.0.2, getting the data from an API and using amcharts4 version 4.10.22.

Has anyone seen an error like this or knows where it may be coming from?

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

**Comment by AndreaChumioque** [comment]
This would be the code on [CodeSanbox](https://codesandbox.io/p/sandbox/amcharts4-linechart-55r2x8?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cm047y9ig00063b5ty3rjd4kf%2522%252C%2522sizes%2522%253A%255B100%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cm047y9ig00023b5tba11ykr3%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cm047y9ig00033b5tp0y43csb%2522%257D%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cm047y9ig00053b5t0rxrujlw%2522%257D%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cm047y9ig00023b5tba11ykr3%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm047y9ig00013b5tyx635l30%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522cm06vz5uv00023b5txyqbzngd%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A9%252C%2522startColumn%2522%253A15%252C%2522endLineNumber%2522%253A9%252C%2522endColumn%2522%253A21%257D%255D%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522cm047y9ig00023b5tba11ykr3%2522%252C%2522activeTabId%2522%253A%2522cm06vz5uv00023b5txyqbzngd%2522%257D%252C%2522cm047y9ig00053b5t0rxrujlw%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm047y9ig00043b5t22l6a1rv%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%257D%255D%252C%2522id%2522%253A%2522cm047y9ig00053b5t0rxrujlw%2522%252C%2522activeTabId%2522%253A%2522cm047y9ig00043b5t22l6a1rv%2522%257D%252C%2522cm047y9ig00033b5tp0y43csb%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cm047y9ig00033b5tp0y43csb%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

I have not been able to reproduce the issue in the sandbox, but in my project code I tried copying the implementation from a demo, to rule out that the implementation from my original chart could be wrong, but with the demo code I am still getting the same error.

**Comment by martynasma** [comment]
We'll need a way to reproduce it, I'm afraid.

**Comment by AndreaChumioque** [comment]
I will try to do that, thanks!
