### ISSUE TITLE
ValueAxis does not work when values are below a certain threshold

### ISSUE THREAD

**Issue by dez1729** [amcharts/amcharts4#2065]
**Codesandbox:**
https://codesandbox.io/s/busy-cache-nizix?fontsize=14&hidenavigation=1&theme=dark

**Description:** 
When the max and min of ValueAxis set individually to below/above a certain value (or sometimes not provided one) the axis disappears completely.

**Affected versions:**
4.8.1 only, 4.8.0 and below seems to work fine.

**Comment by martynasma** [comment]
The codesandbox link you provide does not seem to contain any amCharts code. Can you post it again?

**Comment by dez1729** [comment]
please try again thanks

**Comment by martynasma** [comment]
Fixed in [4.8.2](https://github.com/amcharts/amcharts4/releases/tag/4.8.2).

## [4.8.2] - 2020-01-23

### Added
- `TreeMap.homeDataItem` getter added.

### Fixed
- Sometimes labels were not being truncated properly.
- `ValueAxis` with values <1 might not display labels (since `4.8.1` only).
- Axis syncing was not working on initial view if no animated theme was used.
- Sometimes undefined variables were being restored with default state where they shouldn't. (since `4.8.1` only).

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by dez1729** [comment]
I cannot seem to run my app after upgrading to 4.8.2 or 4.8.3.

I'm getting a bunch of the same error: 
../node_modules/@amcharts/amcharts4/.internal/plugins/annotation/Annotation.d.ts:325:9 - error TS1086: An accessor cannot be declared in an ambient context.

Seems the cause may be typescript version was upgraded to 3.7.x whereas Angular 8 requires <3.6

**Comment by martynasma** [comment]
OK, we found the issue. Apparently TypeScript 3.7. introduced a [breaking change](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#class-field-mitigations).

We've downgraded to TS 3.6 and released a new version of amCharts. It should be fine now.

Make sure you upgrade to amCharts 4.8.4.
