### ISSUE TITLE
Node modules issue

### ISSUE THREAD

**Issue by Varshamathukumalli** [amcharts/amcharts4#546]
Hi,
After upgrading to 73, below issues are observed while building the application

ERROR in node_modules/@amcharts/amcharts4/.internal/core/utils/Object.d.ts(60,117): error TS2536: Type 'Key' cannot be used to index type 'Object'.
node_modules/@amcharts/amcharts4/.internal/core/utils/Object.d.ts(67,109): error TS2536: Type 'Key' cannot be used to index type 'Object'.
node_modules/@amcharts/amcharts4/.internal/core/utils/Object.d.ts(76,116): error TS2536: Type 'Key' cannot be used to index type 'Object'.
node_modules/@amcharts/amcharts4/.internal/core/utils/Type.d.ts(25,32): error TS2304: Cannot find name 'Extract'.

**Comment by Pauan** [comment]
@Varshamathukumalli [Did you put this into your `tsconfig.json`?](https://www.amcharts.com/docs/v4/getting-started/using-typescript-or-es6/#TypeScript_strict_mode)

```json
{
  "compilerOptions": {
    "strictNullChecks": false,
    "strictFunctionTypes": false
  }
}
```

What is your `typescript` version?

**Comment by Pauan** [comment]
@Varshamathukumalli Ah, I see, that's the problem: try upgrading to TypeScript 2.8 or higher.

**Comment by Varshamathukumalli** [comment]
@Pauan , After updating that worked.
Thanks.

**Comment by kishandonepudi** [comment]
As my project is not asking me maintain typescript versions as >=2.7.2 and <2.8.0. My current version is 2.7.2.

Please help

**Comment by Pauan** [comment]
@kishandonepudi You have two possible solutions:

1. You can use `skipLibCheck` in your `tsconfig.json` to disable the errors from AmCharts:

   ```json
   {
     "compilerOptions": {
       "skipLibCheck": true
     }
   }
   ```

2. Or you can use `@ts-ignore` to ignore the errors from the AmCharts imports:

   ```ts
   // @ts-ignore
   import * as am4core from "@amcharts/amcharts4/core";
   // @ts-ignore
   import * as am4charts from "@amcharts/amcharts4/charts";
   ```

**Comment by Davel-11** [comment]
adding:
// @ts-ignore
import * as am4core from "@amcharts/amcharts4/core";
// @ts-ignore
import * as am4charts from "@amcharts/amcharts4/charts";

worked form me, 
without updating typescript to 2.8,

Im using typescript 2.7, angular 6

**Comment by bot101** [comment]
> @kishandonepudi You have two possible solutions:
> 
> 1. You can use `skipLibCheck` in your `tsconfig.json` to disable the errors from AmCharts:
>    ```json
>    {
>      "compilerOptions": {
>        "skipLibCheck": true
>      }
>    }
>    ```
> 2. Or you can use `@ts-ignore` to ignore the errors from the AmCharts imports:
>    ```ts
>    // @ts-ignore
>    import * as am4core from "@amcharts/amcharts4/core";
>    // @ts-ignore
>    import * as am4charts from "@amcharts/amcharts4/charts";
>    ```

Been at this for days. Thanks

**Comment by shalvy** [comment]
I did all that still the same problem as mentioned by @Davel-11
